name: Publish

on:
  release:
    types: [published]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpx @biomejs/biome ci
      - run: pnpm test

  build-and-publish-npm:
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # OIDC token for JSR auth
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpx jsr publish
